version: '3'
services:
  app-server:
    image: deb2511/app-server:v1
    container_name: app-server
    ports:
      - 3000:3000
    networks:
      - app-network
  web-server:
    image: deb2511/web-server:v1
    container_name: web-server
    ports:
      - 80:80
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network      
    volumes:
      - app-volume:/data/db

volumes:
  app-volume:
    driver: local
networks:
  app-network:
    name: app-network
    driver: bridge
