name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the app server Docker image
      run: docker image build ./src/app-server/ --file ./src/app-server/Dockerfile --tag app-server:v1
    - name: Build the web serverDocker image
      run: docker image build ./src/web-server/ --file ./src/web-server/Dockerfile --tag web-server:v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

    - name: Push Images to Docker Hub
      run: |
         docker push $DOCKER_REPOSITORY/app-server:v1
         docker push $DOCKER_REPOSITORY/web-server:v1
      env:
        DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}  

