name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build-Push-DockerHub :

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the app server Docker image
      run: docker image build ./src/app-server/ --file ./src/app-server/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/app-server:v1
    - name: Build the web server Docker image
      run: docker image build ./src/web-server/ --file ./src/web-server/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/web-server:v1
     
    - name: Install Trivy
      run: docker pull aquasecurity/trivy

    - name: Scan app server Docker image with Trivy
      run: docker run --rm -v $(pwd)/src/app-server:/work aquasecurity/trivy --exit-code 1 --severity HIGH,CRITICAL --no-progress /work/Dockerfile

    - name: Scan web server Docker image with Trivy
      run: docker run --rm -v $(pwd)/src/web-server:/work aquasecurity/trivy --exit-code 1 --severity HIGH,CRITICAL --no-progress /work/Dockerfile

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

    - name: Push App Server Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-server:v1
    - name: Push Web Server Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-server:v1
 

